# Generated by Django 3.1.2 on 2020-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_corp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening', models.BooleanField(max_length=100)),
                ('ExpCred', models.BooleanField(max_length=100)),
                ('Overdraft', models.BooleanField(max_length=100)),
                ('IntPlace', models.BooleanField(max_length=100)),
                ('SalProj', models.BooleanField(max_length=100)),
                ('Deposits', models.BooleanField(max_length=100)),
                ('WebApp', models.BooleanField(max_length=100)),
                ('security', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_ind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('security', models.CharField(max_length=100)),
                ('CrCardExist', models.BooleanField(max_length=100)),
                ('DebCardExist', models.CharField(max_length=100)),
                ('PremCardExist', models.CharField(max_length=100)),
                ('RubDep', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('DolDep', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('EurDep', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('MultivDepExist', models.BooleanField(max_length=100)),
                ('CrRealEstate', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('CrWtLoan', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('CrRealEstateAuto', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('Refinancing', models.BooleanField(max_length=100)),
                ('AutoCr', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('Deposits', models.BooleanField(max_length=100)),
                ('Insurance', models.BooleanField(max_length=100)),
                ('Investments', models.BooleanField(max_length=100)),
                ('MobApp', models.BooleanField(max_length=100)),
                ('MobConn', models.BooleanField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening', models.BooleanField(max_length=100)),
                ('revLoan', models.CharField(max_length=100)),
                ('CreditLine', models.CharField(max_length=100)),
                ('RevCreditLine', models.CharField(max_length=100)),
                ('InvestCreditLine', models.CharField(max_length=100)),
                ('AnyCredit', models.CharField(max_length=100)),
                ('AnyCreditEstate', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
                ('Overdraft', models.BooleanField(max_length=100)),
                ('Deposits', models.BooleanField(max_length=100)),
                ('MobBank', models.BooleanField(max_length=100)),
                ('Security', models.DecimalField(decimal_places=1, max_digits=4, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
    ]
