# Generated by Django 3.1.2 on 2020-10-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_auto_20201011_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_ind',
            name='AutoCr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='CrCardExist',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='CrRealEstate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='CrRealEstateAuto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='CrWtLoan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='DebCardExist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='Deposits',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='DolDep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='EurDep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='Insurance',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='Investments',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='MobApp',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='MobConn',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='MultivDepExist',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='PremCardExist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='Refinancing',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='RubDep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_ind',
            name='security',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank_legal',
            name='AnyCreditEstate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank_legal',
            name='Security',
            field=models.CharField(max_length=100),
        ),
    ]
